<!DOCTYPE html>
<html>
<head><script src="/livereload.js?port=1313&mindelay=10&v=2" data-no-instant defer></script>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Exception handling in batch operations with the AggregateException - Jef Claes</title><meta name="viewport" content="width=device-width, initial-scale=1">
	<meta itemprop="name" content="Exception handling in batch operations with the AggregateException">
<meta itemprop="description" content="Doing batch operations and elegantly handling exceptions is a problem which every developer has faced before. In .NET 3.5 or older there is no out-of-the-box solution to handle exceptions in these types of scenarios, without being inconsistent to the normal flow of exception handling. .NET 4 introduces the AggregateException; an exception representing multiple exceptions. The AggregateException was introduced in the first place to be used with the parallel framework, but it can be used in other scenarios as well, such as batch operations.">
<meta itemprop="datePublished" content="2010-05-15T18:34:00&#43;02:00" />
<meta itemprop="dateModified" content="2010-05-15T18:34:00&#43;02:00" />
<meta itemprop="wordCount" content="395">



<meta itemprop="keywords" content=".NET,Best Practices," /><meta property="og:title" content="Exception handling in batch operations with the AggregateException" />
<meta property="og:description" content="Doing batch operations and elegantly handling exceptions is a problem which every developer has faced before. In .NET 3.5 or older there is no out-of-the-box solution to handle exceptions in these types of scenarios, without being inconsistent to the normal flow of exception handling. .NET 4 introduces the AggregateException; an exception representing multiple exceptions. The AggregateException was introduced in the first place to be used with the parallel framework, but it can be used in other scenarios as well, such as batch operations." />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://localhost:1313/2010/05/exception-handling-in-batch-operations-with-the-aggregateexception/" />
<meta property="article:published_time" content="2010-05-15T18:34:00+02:00" />
<meta property="article:modified_time" content="2010-05-15T18:34:00+02:00" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Exception handling in batch operations with the AggregateException"/>
<meta name="twitter:description" content="Doing batch operations and elegantly handling exceptions is a problem which every developer has faced before. In .NET 3.5 or older there is no out-of-the-box solution to handle exceptions in these types of scenarios, without being inconsistent to the normal flow of exception handling. .NET 4 introduces the AggregateException; an exception representing multiple exceptions. The AggregateException was introduced in the first place to be used with the parallel framework, but it can be used in other scenarios as well, such as batch operations."/>
<link href='https://fonts.googleapis.com/css?family=Playfair+Display:700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" media="screen" href="http://localhost:1313/css/normalize.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="http://localhost:1313/css/main.css" />

        <link id="dark-scheme" rel="stylesheet" type="text/css" href="http://localhost:1313/css/dark.css" />

	<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
		<script src="http://localhost:1313/js/main.js"></script>
</head>

<body>
	<div class="container wrapper">
		<div class="header">
	
		<div class="avatar">
			<a href="http://localhost:1313/">
				<img src="https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg" alt="Jef Claes" />
			</a>
		</div>
	
	<h1 class="site-title"><a href="http://localhost:1313/">Jef Claes</a></h1>
	<div class="site-description"><p>On software and life</p><nav class="nav social">
			<ul class="flat"><li><a href="https://github.com/jefclaes" title="Github"><i data-feather="github"></i></a></li><li><a href="/index.xml" title="RSS"><i data-feather="rss"></i></a></li></ul>
		</nav></div>

	<nav class="nav">
		<ul class="flat">
			
			<li>
				<a href="/">Home</a>
			</li>
			
			<li>
				<a href="/post">All posts</a>
			</li>
			
			<li>
				<a href="/about">About</a>
			</li>
			
			<li>
				<a href="/tags">Tags</a>
			</li>
			
		</ul>
	</nav>
</div>


		<div class="post">
			<div class="post-header">
				
					<div class="meta">
						<div class="date">
							<span class="day">15</span>
							<span class="rest">May 2010</span>
						</div>
					</div>
				
				<div class="matter">
					<h1 class="title">Exception handling in batch operations with the AggregateException</h1>
				</div>
			</div>
					
			<div class="markdown">
				<p>Doing batch operations and elegantly handling exceptions is a problem
which every developer has faced before. In .NET 3.5 or older there is no
out-of-the-box solution to handle exceptions in these types of
scenarios, without being inconsistent to the normal flow of exception
handling. .NET 4 introduces the
<a href="http://msdn.microsoft.com/en-us/library/system.aggregateexception.aspx">AggregateException</a>;
an exception representing multiple exceptions. The AggregateException
was introduced in the first place to be used with the <a href="http://msdn.microsoft.com/en-us/concurrency/default.aspx">parallel
framework</a>,
but it can be used in other scenarios as well, such as batch
operations.</p>
<p><!-- raw HTML omitted -->Take a look at the following
example..<!-- raw HTML omitted --></p>
<p>I have a single action which I want to peform in batch. This single
action might throw some exceptions.</p>
<pre><code>   1:  private static void ExecuteSingleAction(int i)

   2:  {

   3:       if (i == 5)            

   4:            throw new ArgumentNullException(&quot;You forgot an argument.&quot;);            

   5:       if (i == 18)

   6:            throw new ArgumentException(&quot;This argument doesn't make sense.&quot;);              

   7:  }
</code></pre>
<p>Most of the exceptions the single action might throw shouldn&rsquo;t break my
whole batch operation. While I&rsquo;m executing the single actions I catch
the exceptions which shouldn&rsquo;t break the batch operation and hold them
in a list of exceptions. The AggregateException has a public constructor
taking an IEnumerable of exceptions. If I catch some exceptions while
executing the single action I throw an AggregateException passing in
that list of exceptions to its constructor.</p>
<pre><code>   1:  private static void ExecuteBatch()

   2:  {

   3:       List&lt;Exception&gt; exceptions = new List&lt;Exception&gt;();

   4:             

   5:       for (int i = 0; i &lt; 100; i++)

   6:       {

   7:            try

   8:            {

   9:                 ExecuteSingleAction(i);

  10:            }

  11:            catch (ArgumentNullException nullRefEx)

  12:            {

  13:                 exceptions.Add(nullRefEx);

  14:            }

  15:            catch (ArgumentException argumentEx)

  16:            {

  17:                 exceptions.Add(argumentEx);

  18:            }             

  19:        }

  20:   

  21:        if (exceptions.Count &gt; 0)           

  22:             throw new AggregateException(exceptions);            

  23:   }
</code></pre>
<p>In the front-end I can catch the AggregateException, run over its
<a href="http://msdn.microsoft.com/en-us/library/system.aggregateexception.innerexceptions(v=VS.100).aspx">InnerExceptions</a>
and act based on the type of exception.</p>
<pre><code>   1:  static void Main(string[] args)

   2:  {

   3:       try

   4:       {

   5:            ExecuteBatch();

   6:       }

   7:       catch (AggregateException aggEx)

   8:       {

   9:            foreach(Exception ex in aggEx.InnerExceptions)

  10:            {                  

  11:                 Console.WriteLine(ex.Message);

  12:   

  13:                 if (ex is ArgumentNullException)

  14:                 {

  15:                      //Do something

  16:                 }

  17:                 if (ex is ArgumentException)

  18:                 {

  19:                     //Do something else

  20:                 }

  21:              }

  22:       }

  23:   

  24:       Console.ReadLine();

  25:  }
</code></pre>
<p>The result looks like this.</p>
<p><a href="/post/images/2010-05-15-exception-handling-in-batch-operations-with-the-aggregateexception-ResultAggregateException.png"><img src="/post/images/thumbnails/2010-05-15-exception-handling-in-batch-operations-with-the-aggregateexception-ResultAggregateException.png" alt=""></a></p>
<p><!-- raw HTML omitted -->More scenario&rsquo;s?<!-- raw HTML omitted --></p>
<p>Can you imagine other scenarios where the AggregateException might be
able to add some value?</p>
<p><!-- raw HTML omitted -->Related post: <a href="http://jclaes.blogspot.com/2010/05/handling-aggregateexception.html">Handling the
AggregateException</a><!-- raw HTML omitted --></p>

			</div>

			<div class="tags">
				
					
						<ul class="flat">
							
							<li><a href="/tags/.net">.NET</a></li>
							
							<li><a href="/tags/best-practices">Best Practices</a></li>
							
						</ul>
					
				
			</div></div>
	</div>
	<div class="footer wrapper">
	<nav class="nav">
		<div>2010  <a href="https://github.com/knadh/hugo-ink">Ink</a> theme on <a href="https://gohugo.io">Hugo</a></div>
	</nav>
</div>

<script>feather.replace()</script>
</body>
</html>
